# BEGIN_KITTY_FONTS
font_family      family="Maple Mono Normal NF CN"
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 12.0
# END_KITTY_FONTS

# Color Scheme
background_opacity 0.88
background_blur 64

# Window Layout
enlable_layout *
remember_window_size  yes
hide_window_decorations yes

# Cursor color
# cursor none
# Cursor Trail
cursor_trail 1

# Tab Bar
tab_bar_margin_width 0.0
tab_bar_margin_height 0.0 0.0
tab_bar_align left
# tab_activity_sybol none
tab_bar_edge top
tab_bar_style custom
# tab_separator " "
# tab_separator "|"
tab_powerline_style round
active_tab_font_style bold-italic
inactive_tab_font_style normal
tab_title_template "{index} {title.split('/')[-1] if '/' in title else (title.split()[0] if len(title) > 18 else title)}"
# active_tab_title_template " {index} {f'{title[:12]}…'} {bell_symbol}{activity_symbol} "
