# Tab management
map ctrl+1 goto_tab 1
map ctrl+2 goto_tab 2
map ctrl+3 goto_tab 3
map ctrl+4 goto_tab 4
map ctrl+5 goto_tab 5
map ctrl+6 goto_tab 6
map ctrl+7 goto_tab 7
map ctrl+8 goto_tab 8
map ctrl+9 goto_tab 9
map ctrl+0 nth_window 999

map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9
map alt+0 nth_window 999

map ctrl+shift+t new_tab_with_cwd
map ctrl+shift+enter new_window_with_cwd
map ctrl+shift+n new_os_window_with_cwd

# window management
# map alt+h neighboring_window left
# map alt+j neighboring_window down
# map alt+k neighboring_window up
# map alt+l neighboring_window right
map ctrl+j kitten pass_keys.py neighboring_window bottom ctrl+j
map ctrl+k kitten pass_keys.py neighboring_window top    ctrl+k
map ctrl+h kitten pass_keys.py neighboring_window left   ctrl+h
map ctrl+l kitten pass_keys.py neighboring_window right  ctrl+l

# resize windows
map alt+left resize_window narrower 3
map alt+right resize_window wider 3
map alt+up resize_window taller 3
map alt+down resize_window shorter 3
# reset all windows in the tab to default sizes
map alt+home resize_window reset

# 默认切换布局 ctrl+shift+l
# 切换布局为stack
map f1 toggle_layout stack

# goto sessions
# 按下ctrl+b，然后松开，再按n
map alt+q goto_session -1
map alt+h goto_session sessions/home.kitty-session
map alt+n goto_session sessions/notes.kitty-session
map alt+c goto_session sessions/config.kitty-session
map alt+e goto_session sessions/chezmoi.kitty-session
map alt+p goto_session sessions/projects.kitty-session
map alt+shift+s save_as_session --use-foreground-process --base-dir ~/.config/kitty/sessions

# 使用 Ctrl+Shift+y 抓取上一条命令输出并直接写入 Wayland 剪贴板
map ctrl+shift+y launch --stdin-source=@last_cmd_output --type=background wl-copy
