# Tab management
map ctrl+1 goto_tab 1
map ctrl+2 goto_tab 2
map ctrl+3 goto_tab 3
map ctrl+4 goto_tab 4
map ctrl+5 goto_tab 5
map ctrl+6 goto_tab 6
map ctrl+7 goto_tab 7
map ctrl+8 goto_tab 8
map ctrl+9 goto_tab 9
map ctrl+0 goto_tab 10
map ctrl+p nth_window -1

# window management
# map alt+h neighboring_window left
# map alt+j neighboring_window down
# map alt+k neighboring_window up
# map alt+l neighboring_window right
map ctrl+j kitten pass_keys.py neighboring_window bottom ctrl+j
map ctrl+k kitten pass_keys.py neighboring_window top    ctrl+k
map ctrl+h kitten pass_keys.py neighboring_window left   ctrl+h
map ctrl+l kitten pass_keys.py neighboring_window right  ctrl+l

# resize windows
map alt+left resize_window narrower 3
map alt+right resize_window wider 3
map alt+up resize_window taller 3
map alt+down resize_window shorter 3
# reset all windows in the tab to default sizes
map alt+home resize_window reset

# 默认切换布局 ctrl+shift+l
# 切换布局为stack
map f1 toggle_layout stack

