# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME

# Key Bindings
include keys.conf

# Plugins
include plugins.conf

# basic 
include basic.conf

# startup seesion
startup_session workspace.conf

