[plugin]
deps = [{ use = "yazi-rs/plugins:full-border", rev = "06e5fe1" }, { use = "yazi-rs/plugins:max-preview", rev = "06e5fe1" }, { use = "yazi-rs/plugins:smart-filter", rev = "06e5fe1" }, { use = "yazi-rs/plugins:git", rev = "dc11879" }]

[flavor]
deps = []
