[[manager.prepend_keymap]]
on = "q"
run = "close"
desc = "Close the current tab, or quit if it is last tab"

[[manager.prepend_keymap]]
on = "<C-c>"
run = "quit"
desc = "Exit the process"

[[manager.prepend_keymap]]
on = "H"
run = "tab_switch -1 --relative"
desc = "Switch to the previous tab"

[[manager.prepend_keymap]]
on = "L"
run = "tab_switch 1 --relative"
desc = "Switch to the next tab"

[[manager.prepend_keymap]]
on = "["
run = "back"
desc = "Go back to the previous directory"

[[manager.prepend_keymap]]
on = "]"
run = "forward"
desc = "Go forward to the next directory"

# goto
[[manager.prepend_keymap]]
on = ["g", "c"]
run = "cd ~/.config"
desc = "Go to the config directory"

[[manager.prepend_keymap]]
on = ["g", "C"]
run = "cd ~/.cache"
desc = "Go to the cache directory"

[[manager.prepend_keymap]]
on = ["g", "<Space>"]
run = "cd --interactive"
desc = "Go to a directory interactively"

[[manager.prepend_keymap]]
on = ["g", "h"]
run = "cd ~"
desc = "Go to the home directory"

[[manager.prepend_keymap]]
on = ["g", "l"]
run = "cd ~/.local"
desc = "Go to the local directory"

[[manager.prepend_keymap]]
on = ["g", "t"]
run = "cd ~/.local/share/Trash/files"
desc = "Go to the trash directory"

[[manager.prepend_keymap]]
on = ["g", "T"]
run = "cd ~/.local/share/nvim/mini.files/trash"
desc = "Go to the nvim trash directory"

[[manager.prepend_keymap]]
on = ["g", "d"]
run = "cd ~/Downloads"
desc = "Go to the Downloads directory"

[[manager.prepend_keymap]]
on = ["g", "D"]
run = "cd ~/Documents"
desc = "Go to the Documents directory"

[[manager.prepend_keymap]]
on = ["g", "z"]
run = "cd ~/Downloads/Zip"
desc = "Go to the Zip directory"

[[manager.prepend_keymap]]
on = ["g", "n"]
run = "cd ~/Notes"
desc = "Go to the Notes directory"

[[manager.prepend_keymap]]
on = ["g", "o"]
run = "cd ~/OpenSource"
desc = "Go to the OpenSource directory"

[[manager.prepend_keymap]]
on = ["g", "O"]
run = "cd ~/Downloads/Doc"
desc = "Go to the Office directory"

[[manager.prepend_keymap]]
on = ["g", "Z"]
run = "cd ~/Desktop"
desc = "Go to the Desktop directory"

[[manager.prepend_keymap]]
on = ["g", "M"]
run = "cd ~/Music"
desc = "Go to the Music directory"

[[manager.prepend_keymap]]
on = ["g", "p"]
run = "cd ~/Projects/"
desc = "Go to the Projects directory"

[[manager.prepend_keymap]]
on = ["g", "P"]
run = "cd ~/Pictures"
desc = "Go to the pictures directory"

[[manager.prepend_keymap]]
on = ["g", "V"]
run = "cd ~/Videos"
desc = "Go to the Videos directory"

# plugins
[[manager.prepend_keymap]]
on = "T"
run = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"

[[manager.prepend_keymap]]
on = "F"
run = "plugin smart-filter"
desc = "Smart filter"

[[manager.prepend_keymap]]
on = ["g", "s"]
run = "plugin vcs-files"
desc = "Show Git file changes"

# eza-preview
[[manager.prepend_keymap]]
on = "E"
run = "plugin eza-preview"
desc = "Toggle tree/list dir preview"

[[manager.prepend_keymap]]
on = "-"
run = "plugin eza-preview --args='--inc-level'"
desc = "Increment tree level"

[[manager.prepend_keymap]]
on = "_"
run = "plugin eza-preview --args='--dec-level'"
desc = "Decrement tree level"

[[manager.prepend_keymap]]
on = "$"
run = "plugin eza-preview --args='--toggle-follow-symlinks'"
desc = "Toggle tree follow symlinks"

# searchjump
[[manager.prepend_keymap]]
on = ["s"]
run = "plugin searchjump -- autocd"
desc = "searchjump mode"

[[manager.prepend_keymap]]
on = ["S"]
run = "plugin searchjump"
desc = "searchjump mode"

[[manager.prepend_keymap]]
on = "i"
run = "search --via=fd"
desc = "Search files by name via fd"

[[manager.prepend_keymap]]
on = "I"
run = "search --via=rg"
desc = "Search files by content via ripgrep"
