[mgr]
ratio = [1, 2, 2]
sort_by = "extension"

# [opener]
# extract = [
#   { run = 'unzip -O gb18030 "$@"', desc = "Extract with encoding", for = "unix" },
#   { run = 'ya pub extract --list "$@"', desc = "Extract here", for = "unix" },
#   { run = 'ya pub extract --list %*', desc = "Extract here", for = "windows" },
# ]

[[opener.extract]]
run = 'unzip -O gb18030 "$@"'
desc = "Extract with encoding"
for = "unix"

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"

[[plugin.prepend_previewers]]
name = "*/"
run = "eza-preview"

[[plugin.prepend_previewers]]
name = "*.md"
run = "glow"

[[plugin.prepend_previewers]]
mime = "application/*zip"
run = "ouch"

[[plugin.prepend_previewers]]
mime = "application/x-tar"
run = "ouch"

[[plugin.prepend_previewers]]
mime = "application/x-bzip2"
run = "ouch"

[[plugin.prepend_previewers]]
mime = "application/x-7z-compressed"
run = "ouch"

[[plugin.prepend_previewers]]
mime = "application/x-rar"
run = "ouch"

[[plugin.prepend_previewers]]
mime = "application/x-xz"
run = "ouch"

[[plugin.prepend_previewers]]
mime = "application/xz"
run = "ouch"
