[manager]
ratio = [1, 2, 2]
sort_by = "extension"

[[opener.extract]]
run = 'unzip -O gb18030 "$@"'
desc = "Extract with encoding"
for = "unix"

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"

[[plugin.prepend_previewers]]
name = "*/"
run = "eza-preview"
